In [40]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.read_csv('homeprices.csv')

In [3]:
df

,town,area,price
0,monroe township,2600,550000
1,monroe township,3000,565000
2,monroe township,3200,610000
3,monroe township,3600,680000
4,monroe township,4000,725000
5,west windsor,2600,585000
6,west windsor,2800,615000
7,west windsor,3300,650000
8,west windsor,3600,710000
9,robinsville,2600,575000


In [4]:
dummies = pd.get_dummies(df, dtype='int')

In [6]:
dummies.head()

,area,price,town_monroe township,town_robinsville,town_west windsor
0,2600,550000,1,0,0
1,3000,565000,1,0,0
2,3200,610000,1,0,0
3,3600,680000,1,0,0
4,4000,725000,1,0,0


In [7]:
final = dummies.drop('town_west windsor', axis=1)

In [8]:
final

,area,price,town_monroe township,town_robinsville
0,2600,550000,1,0
1,3000,565000,1,0
2,3200,610000,1,0
3,3600,680000,1,0
4,4000,725000,1,0
5,2600,585000,0,0
6,2800,615000,0,0
7,3300,650000,0,0
8,3600,710000,0,0
9,2600,575000,0,1


In [12]:
X = final.drop('price', axis='columns')
y = final['price']

In [13]:
lg_model = LinearRegression()
lg_model.fit(X, y)

LinearRegression()

In [16]:
pred = lg_model.predict(X)

In [19]:
lg_model.score(X, y)

0.9573929037221873

In [24]:
lg_model.predict([[2800, 1, 0]]) # 2800 sqr ft home in town_monroe township

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([565089.22812299])

In [25]:
lg_model.predict([[2800, 0, 1]]) # 2800 sqr ft home in town_robinsville

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [23]:
lg_model.predict([[3400, 0, 0]]) # 3400 sqr ft home in west windsor

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.66845839])

In [17]:
dataf = pd.DataFrame({'actual_price': y, 'predicted_price': pred})

## Label/One hot encoder 

In [32]:
df1 = pd.read_csv('homeprices.csv')

In [33]:
df1

,town,area,price
0,monroe township,2600,550000
1,monroe township,3000,565000
2,monroe township,3200,610000
3,monroe township,3600,680000
4,monroe township,4000,725000
5,west windsor,2600,585000
6,west windsor,2800,615000
7,west windsor,3300,650000
8,west windsor,3600,710000
9,robinsville,2600,575000


In [34]:
df1['town'] = np.where(df1['town'] == 'monroe township', 0, df1['town'])
df1['town'] = np.where(df1['town'] == 'west windsor', 2, df1['town'])
df1['town'] = np.where(df1['town'] == 'robinsville', 1, df1['town'])

In [36]:
df1

,town,area,price
0,0,2600,550000
1,0,3000,565000
2,0,3200,610000
3,0,3600,680000
4,0,4000,725000
5,2,2600,585000
6,2,2800,615000
7,2,3300,650000
8,2,3600,710000
9,1,2600,575000


In [37]:
le = LabelEncoder()

In [38]:
dfle = df1
dfle.town = le.fit_transform(dfle.town)

In [39]:
dfle

,town,area,price
0,0,2600,550000
1,0,3000,565000
2,0,3200,610000
3,0,3600,680000
4,0,4000,725000
5,2,2600,585000
6,2,2800,615000
7,2,3300,650000
8,2,3600,710000
9,1,2600,575000


In [41]:
X = dfle[['town', 'area']].values
y = dfle['price'].values

In [44]:
col_transf = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder= 'passthrough')

In [45]:
X = col_transf.fit_transform(X)

In [47]:
X = X[:, 1:]

In [49]:
lg_model.fit(X, y)

LinearRegression()

In [58]:
lg_model.predict([[0, 1, 3400]]) # 3400 sqr ft home in monroe township / robinsville

array([681241.6684584])

In [59]:
lg_model.predict([[1, 0, 2800]]) # 2800 sqr ft home in robbinsville / monroe township

array([590775.63964739])

In [69]:
lg_model.predict([[2, 0, 4000]]) # 2800 sqr ft home in west windsor

array([768738.98086433])

In [ ]:
#'monroe township', 0, df1['town'])
#'west windsor', 2, df1['town'])
#'robinsville', 1, df1['town'])